#!/usr/bin/env python3
"""Build the temperature-sweep configs + work plan for the 10k harvest.

Babel has no per-run temperature override -- temperature lives in the agent
config -- so a *distribution* over temperature has to become a set of configs
plus a plan that says how many runs each one gets.

We discretise a normal centred on MEAN, truncated to [LO, HI], onto a grid of
STEP-spaced temperatures, and emit one config per grid point. The plan file is
one config path per run, shuffled, so a worker's slice is an unbiased sample.

Truncation matters: collapse is only *measured* over 0.2-1.0 (every pilot run
was t=0.7), so HI is a deliberate, bounded step past the evidence rather than a
normal's open upper tail.
"""

import argparse
import math
import random
from collections import Counter
from pathlib import Path

CONFIG_TEMPLATE = """\
# AUTO-GENERATED by scripts/make_temp_configs.py -- do not hand-edit.
# One config per grid temperature; run counts are weighted by a normal
# centred on {mean} (sd {sd}) truncated to [{lo}, {hi}]. See the plan file.
#
# max_iterations={iterations}: we harvest COLLAPSE samples only. Healthy
# negatives are GENERATED (91% yield), not mined from late-collapse runs, so
# the old 24-iteration budget bought nothing. Measured on 100 pilot runs:
# onset+3 <= 15 for 80% of runs at 62% of the compute of 24 -> ~29% more
# usable positives per GPU-hour. Cost: loses the ~10% that onset at 16+.

fetcher_config:
  fetcher: "sharegpt"
  data_path: "data/seeds_10k.json"   # 10,000 real ShareGPT openings
  min_messages: 1        # curated seeds are pre-trimmed; some are a single human turn
  max_messages: 6

analyzer_config:
  analyzer: "similarity"
  analyze_window: 10

agent_configs:
  - provider: "ollama_company"
    model: "qwen2.5:3b-instruct-fp16"
    system_prompt: "You are a helpful assistant participating in a conversation."
    temperature: {temp}
    max_tokens: 512
    frequency_penalty: 0.0    # do NOT discourage repetition -- we WANT collapse
    presence_penalty: 0.0
    top_p: 1.0

agent_selection_method: "round_robin"

max_iterations: {iterations}
max_total_characters: 1000000
output_dir: "{outdir}"
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=10000, help="total runs")
    ap.add_argument("--mean", type=float, default=1.0)
    ap.add_argument("--sd", type=float, default=0.2)
    ap.add_argument("--lo", type=float, default=0.2)
    ap.add_argument("--hi", type=float, default=1.2)
    ap.add_argument("--step", type=float, default=0.05)
    ap.add_argument("--iterations", type=int, default=15)
    ap.add_argument("--config-dir", default="configs/temp_sweep")
    ap.add_argument("--plan", default=".log/harvest_plan.txt")
    ap.add_argument(
        "--results-dir", default="/dais/fs/scratch/fash/results/qwen10k"
    )
    ap.add_argument("--rng-seed", type=int, default=0)
    args = ap.parse_args()

    cfg_dir = Path(args.config_dir)
    cfg_dir.mkdir(parents=True, exist_ok=True)

    # --- grid + truncated-normal weights ----------------------------------
    steps = int(round((args.hi - args.lo) / args.step))
    temps = [round(args.lo + i * args.step, 3) for i in range(steps + 1)]

    def pdf(x: float) -> float:
        z = (x - args.mean) / args.sd
        return math.exp(-0.5 * z * z)

    weights = [pdf(t) for t in temps]
    total_w = sum(weights)
    weights = [w / total_w for w in weights]

    # Largest-remainder apportionment so the counts sum to exactly n.
    raw = [w * args.n for w in weights]
    counts = [int(math.floor(r)) for r in raw]
    short = args.n - sum(counts)
    order = sorted(
        range(len(temps)), key=lambda i: raw[i] - counts[i], reverse=True
    )
    for i in order[:short]:
        counts[i] += 1
    assert sum(counts) == args.n, (sum(counts), args.n)

    # --- write one config per grid temperature ----------------------------
    plan: list[str] = []
    realized: Counter = Counter()
    written = 0
    for temp, count in zip(temps, counts):
        if count == 0:
            continue
        path = cfg_dir / f"qwen_t{temp:.2f}".replace(".", "_")
        path = path.with_suffix(".yaml")
        path.write_text(
            CONFIG_TEMPLATE.format(
                temp=temp,
                iterations=args.iterations,
                outdir=args.results_dir,
                mean=args.mean,
                sd=args.sd,
                lo=args.lo,
                hi=args.hi,
            )
        )
        plan.extend([str(path)] * count)
        realized[temp] = count
        written += 1

    # --- shuffle so any contiguous slice is an unbiased sample ------------
    random.Random(args.rng_seed).shuffle(plan)
    plan_path = Path(args.plan)
    plan_path.parent.mkdir(parents=True, exist_ok=True)
    plan_path.write_text("\n".join(plan) + "\n")

    # --- report ------------------------------------------------------------
    print(
        f"normal(mean={args.mean}, sd={args.sd}) truncated to "
        f"[{args.lo}, {args.hi}], step {args.step}"
    )
    print(f"{written} configs -> {cfg_dir}/")
    print(f"plan: {len(plan)} runs -> {plan_path}")
    print(f"max_iterations = {args.iterations}\n")
    print("  temp   runs   share  histogram")
    for t in sorted(realized):
        c = realized[t]
        share = 100 * c / len(plan)
        print(f"  {t:4.2f}  {c:5d}  {share:5.1f}%  {'#' * int(share * 1.6)}")
    mean_t = sum(t * c for t, c in realized.items()) / len(plan)
    above = sum(c for t, c in realized.items() if t > 1.0)
    print(f"\nrealized mean temp = {mean_t:.3f}")
    print(
        f"runs above t=1.0 (beyond measured evidence): {above} "
        f"({100 * above / len(plan):.0f}%)"
    )


if __name__ == "__main__":
    main()
