#!/usr/bin/env python3
"""Build the babel-ai configs + run plans for one DAgger iteration.

DAgger (Method B) rolls the CURRENT policy out in the self-loop, has an expert
grade the states it actually visited, retrains on those, and repeats. This
script produces the rollout side: the configs babel-ai consumes.

Plan of record: internship-hpc-repo-template/doc/Project/dagger_plan.md

TWO PHASES, DISJOINT SEEDS -- this is the part that must not be got wrong.

    phase=train  seeds 30..279  the rollouts we LABEL and TRAIN on
    phase=eval   seeds 0..29     the BEFORE/AFTER seeds (v6 already ran these,
                                 so BEFORE is free); held out w.r.t. training

Both slices come from data/seeds_unseen_hgh_500.json (openers held out of the
seeds_10k harvest, so nothing here was in Method A's training data either). The
split is enforced here, in one place, rather than left to whoever writes the
sbatch line.

CONFIG SHAPE IS DELIBERATELY IDENTICAL TO v6's SELF-LOOP TEST
(history_window 5, 28 iterations, max_tokens 512, top_p 0.8, similarity analyzer
with analyze_window 10, and the same three system-prompt conditions) -- i.e. the
shape used by /dais/fs/scratch/fash/results/livetest_v6_L3_selfloop, which IS our
BEFORE measurement. That match is the whole reason BEFORE costs no GPU.

Do not "improve" the config shape mid-experiment -- comparability is the point.

WHY A TEMPERATURE DISTRIBUTION rather than one temperature: the model learned
collapse from data generated at temp ~ N(1.0, 0.2). babel has no per-run temp
override, so the distribution becomes a grid of configs plus a plan file weighted
by the normal (the harvest's trick, inherited from make_v4_livetest_configs.py).

Usage (pure CPU, writes files only):
  # collect the rollouts to learn from (policy = v6-L3)
  python scripts/make_dagger_configs.py --iter 1 --phase train \
      --model /u/fash/internship-hpc-repo-template/models/end-token-A-qwen3b-v6-L3
  # measure the retrained policy on the BEFORE seeds
  python scripts/make_dagger_configs.py --iter 1 --phase eval \
      --model /u/fash/internship-hpc-repo-template/models/end-token-A-qwen3b-dagger-i1

Then (ASK THE USER FIRST -- never submit unprompted):
  sbatch scripts/inference/dagger_rollout.slurm.sh   # reads the plans
"""
from __future__ import annotations

import argparse
import math
import random
import re
from collections import Counter
from pathlib import Path

# Seed slices.
#
# SEEDS 0-29 ARE ALREADY SPENT. v6's evaluations consumed indices 0..29 (30
# distinct seeds across 37 result directories). Those runs are our BEFORE
# measurement, so the DAgger *training* rollouts must not touch them -- if they
# did, the after-model would have trained on the seeds it is scored on.
#
#   eval  = 0..29     the BEFORE/AFTER seeds. Both models run the SAME 30, which
#                     makes it a PAIRED comparison (far more power at this n).
#                     Held out w.r.t. DAgger training, which is what matters.
#   train = 30..279   never touched by anything. What we roll out and label.
#
# The corpus has 500 entries, so 280..499 stay in reserve for a second iteration.
SEED_BASE = {"train": 30, "eval": 0}
SLICE_SIZE = {"train": 250, "eval": 30}

# seeds_unseen_hgh_500.json, NOT seeds_unseen_500.json. hgh = H,G,H =
# Human, GPT, Human: it restores the real first THREE messages of each seed
# conversation. The older file kept only the opening human turn, so runs began
# with nothing to continue from. Every v6 config uses the hgh file, and the two
# are not interchangeable.
SEED_FILE = "data/seeds_unseen_hgh_500.json"

# The three system-prompt conditions, unchanged from the v4 live test so the
# numbers line up condition-by-condition.
SEEN = "You are a helpful assistant participating in a conversation."
UNSEEN = ("You are a curious debate partner who challenges ideas respectfully "
          "and keeps the discussion moving forward.")
CONDITIONS = {"nosys": None, "seen": SEEN, "unseen": UNSEEN}

TEMPLATE = """\
# AUTO-GENERATED by make_dagger_configs.py -- do not hand-edit.
# DAgger iter={it} | phase={phase} | condition={cond} | temp={temp}
# seeds {seed_lo}..{seed_hi} (from N({mean},{sd}) trunc [{lo},{hi}])
fetcher_config:
  fetcher: "sharegpt"
  data_path: "{seedfile}"
  min_messages: 1
  max_messages: 6

analyzer_config:
  analyzer: "similarity"
  analyze_window: 10

agent_configs:
  - provider: "local_hf"
    model: "{model}"
{sysline}    temperature: {temp}
    max_tokens: 512
    frequency_penalty: 0.0
    presence_penalty: 0.0
    top_p: 0.8

agent_selection_method: "round_robin"

history_window: 5
max_iterations: 28
max_total_characters: 1000000
output_dir: "{outdir}"
"""


def grid(mean, sd, lo, hi, step, n):
    """n runs spread over a temperature grid, weighted by N(mean, sd).

    Copied (not imported) from make_v4_livetest_configs.py on purpose: that file
    belongs to the v4/v5 track and this one must not break if it changes.
    """
    steps = int(round((hi - lo) / step))
    temps = [round(lo + i * step, 3) for i in range(steps + 1)]
    w = [math.exp(-0.5 * ((t - mean) / sd) ** 2) for t in temps]
    tot = sum(w)
    raw = [wi / tot * n for wi in w]
    counts = [int(math.floor(r)) for r in raw]
    short = n - sum(counts)
    for i in sorted(range(len(temps)), key=lambda i: raw[i] - counts[i],
                    reverse=True)[:short]:
        counts[i] += 1
    assert sum(counts) == n
    return temps, counts


def check_registered(model_path: str) -> None:
    """babel validates `model` against the LocalHFModels enum, so an unregistered
    path fails config validation at RUN time -- after the GPU is already
    allocated. Catch it here, on CPU, and print the exact line to add.

    Deliberately does NOT edit enums.py itself: that file is shared with the
    v4/v5 live tests, and a silent append is not the kind of surprise this
    project can afford.
    """
    enums = Path(__file__).resolve().parents[1] / "src" / "api" / "enums.py"
    text = enums.read_text()
    if model_path in text:
        return
    name = re.sub(r"[^A-Za-z0-9]+", "_", Path(model_path).name).upper()
    raise SystemExit(
        f"\n{model_path}\nis not registered in {enums} (class LocalHFModels).\n"
        f"babel would fail config validation at run time. Add this entry:\n\n"
        f'    {name} = (\n        "{model_path}"\n    )\n'
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iter", type=int, required=True,
                    help="DAgger iteration: 1 = first retrain off v6-L3")
    ap.add_argument("--phase", choices=("train", "eval"), required=True,
                    help="train = rollouts we label; eval = held-out measurement")
    ap.add_argument("--model", required=True, help="policy checkpoint path")
    ap.add_argument("--tag", default="",
                    help="suffix for result dirs, e.g. 'closed'/'open' at i1")
    ap.add_argument("--n", type=int, default=None,
                    help="runs PER CONDITION (default 40 train / 30 eval)")
    ap.add_argument("--mean", type=float, default=1.0)
    ap.add_argument("--sd", type=float, default=0.2)
    ap.add_argument("--lo", type=float, default=0.2)
    ap.add_argument("--hi", type=float, default=1.2)
    ap.add_argument("--step", type=float, default=0.05)
    ap.add_argument("--config-dir", default="configs/dagger")
    ap.add_argument("--results-root", default="/dais/fs/scratch/fash/results")
    ap.add_argument("--rng-seed", type=int, default=0)
    args = ap.parse_args()

    check_registered(args.model)

    # 40/condition = 120 train rollouts (~1.5 GPU-h at the measured ~80 runs/h);
    # 48/condition = 144 eval runs, matching the v4 live test exactly.
    n = args.n if args.n is not None else (40 if args.phase == "train" else 30)
    if n > SLICE_SIZE[args.phase]:
        raise SystemExit(f"--n {n} exceeds the {SLICE_SIZE[args.phase]}-seed "
                         f"{args.phase} slice")

    base = SEED_BASE[args.phase]
    tag = f"_{args.tag}" if args.tag else ""
    cfg_dir = Path(args.config_dir)
    cfg_dir.mkdir(parents=True, exist_ok=True)
    temps, counts = grid(args.mean, args.sd, args.lo, args.hi, args.step, n)

    for cond, sysprompt in CONDITIONS.items():
        sysline = ("" if sysprompt is None
                   else f'    system_prompt: "{sysprompt}"\n')
        stem = f"i{args.iter}{tag}_{args.phase}_{cond}"
        outdir = f"{args.results_root}/dagger_{stem}"
        plan = []
        for temp, count in zip(temps, counts):
            if not count:
                continue
            p = (cfg_dir / f"{stem}_t{temp:.2f}".replace(".", "_")
                 ).with_suffix(".yaml")
            p.write_text(TEMPLATE.format(
                it=args.iter, phase=args.phase, cond=cond, temp=temp,
                seed_lo=base, seed_hi=base + n - 1,
                mean=args.mean, sd=args.sd, lo=args.lo, hi=args.hi,
                model=args.model, sysline=sysline, outdir=outdir,
                seedfile=SEED_FILE))
            plan += [str(p)] * count
        random.Random(args.rng_seed).shuffle(plan)
        plan_path = Path(f".log/dagger_{stem}_plan.txt")
        plan_path.parent.mkdir(parents=True, exist_ok=True)
        plan_path.write_text("\n".join(plan) + "\n")
        print(f"[{cond:6s}] {len(plan):3d} runs  seeds {base}..{base + n - 1}  "
              f"sysprompt={'YES' if sysprompt else 'no ':3s}  -> {plan_path}")
        print(f"           configs: {len(Counter(plan))} temps  out: {outdir}")

    print(f"\nphase={args.phase}  SEED_BASE={base}  seeds={SEED_FILE}")
    print("  (train=30..279 / eval=0..29 -- disjoint; eval seeds are v6's, so"
          " the BEFORE run already exists)")
    print(f"temps span {temps[0]}..{temps[-1]}, weighted N({args.mean},{args.sd})"
          f" trunc [{args.lo},{args.hi}]")
    print(f"model: {args.model}")
    print(f"\nnext:  SEED_BASE={base} ITER={args.iter} PHASE={args.phase}"
          f"{f' TAG={args.tag}' if args.tag else ''}"
          f" sbatch scripts/inference/dagger_rollout.slurm.sh")


if __name__ == "__main__":
    main()
