#!/usr/bin/env python3
"""Build the v4 live-test configs + plans: 3 system-prompt conditions, each with
a TEMPERATURE DISTRIBUTION (not a single temp), matching how the harvest was run.

Why a distribution: the model learned collapse from data generated at
temperature ~ N(1.0, 0.2) truncated [0.2, 1.2]. Fixing one temp shows one slice;
sweeping the distribution shows how firing/collapse behave across the same spread
the model trained under. babel has no per-run temp override, so a distribution
becomes a grid of configs + a plan weighted by the normal (harvest's trick).

Three conditions, identical except the system prompt:
  nosys   -- no system prompt          (apples-to-apples vs v3's 47%)
  seen    -- prompt #0 from the training bank (did training-with-prompts work)
  unseen  -- a prompt NOT in the bank   (real generalization; v3 scored 0.000
             with ANY system prompt)

Each condition gets N runs across the temp grid, and each condition runs the SAME
seeds (SEED_OFFSET 0..N-1 is applied per condition by the slurm), so differences
are attributable to the system prompt, not the seeds.
"""
import argparse
import math
import random
from collections import Counter
from pathlib import Path

MODEL = "/u/fash/internship-hpc-repo-template/models/end-token-A-qwen3b-v4"

# prompt #0 in data/system_prompts.json (the model trained on it); also the exact
# string v3 died on.
SEEN = "You are a helpful assistant participating in a conversation."
# deliberately NOT in the 10-prompt training bank -> tests generalization.
UNSEEN = ("You are a curious debate partner who challenges ideas respectfully "
          "and keeps the discussion moving forward.")

CONDITIONS = {
    "nosys":  None,
    "seen":   SEEN,
    "unseen": UNSEEN,
}

TEMPLATE = """\
# AUTO-GENERATED by make_v4_livetest_configs.py -- do not hand-edit.
# v4 live test | condition={cond} | temp={temp} (from N({mean},{sd}) trunc [{lo},{hi}])
fetcher_config:
  fetcher: "sharegpt"
  data_path: "data/seeds_unseen_500.json"
  min_messages: 1
  max_messages: 6

analyzer_config:
  analyzer: "similarity"
  analyze_window: 10

agent_configs:
  - provider: "local_hf"
    model: "{model}"
{sysline}    temperature: {temp}
    max_tokens: 512
    frequency_penalty: 0.0
    presence_penalty: 0.0
    top_p: 0.8

agent_selection_method: "round_robin"

history_window: 5
max_iterations: 28
max_total_characters: 1000000
output_dir: "{outdir}"
"""


def grid(mean, sd, lo, hi, step, n):
    steps = int(round((hi - lo) / step))
    temps = [round(lo + i * step, 3) for i in range(steps + 1)]
    w = [math.exp(-0.5 * ((t - mean) / sd) ** 2) for t in temps]
    tot = sum(w)
    raw = [wi / tot * n for wi in w]
    counts = [int(math.floor(r)) for r in raw]
    short = n - sum(counts)
    for i in sorted(range(len(temps)), key=lambda i: raw[i] - counts[i],
                    reverse=True)[:short]:
        counts[i] += 1
    assert sum(counts) == n
    return temps, counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=48, help="runs per condition")
    ap.add_argument("--mean", type=float, default=1.0)
    ap.add_argument("--sd", type=float, default=0.2)
    ap.add_argument("--lo", type=float, default=0.2)
    ap.add_argument("--hi", type=float, default=1.2)
    ap.add_argument("--step", type=float, default=0.05)
    ap.add_argument("--config-dir", default="configs/livetest_v4")
    ap.add_argument("--results-root", default="/dais/fs/scratch/fash/results")
    ap.add_argument("--rng-seed", type=int, default=0)
    args = ap.parse_args()

    cfg_dir = Path(args.config_dir)
    cfg_dir.mkdir(parents=True, exist_ok=True)
    temps, counts = grid(args.mean, args.sd, args.lo, args.hi, args.step, args.n)

    for cond, sysprompt in CONDITIONS.items():
        sysline = ("" if sysprompt is None
                   else f'    system_prompt: "{sysprompt}"\n')
        outdir = f"{args.results_root}/livetest_v4_{cond}"
        plan = []
        for temp, count in zip(temps, counts):
            if not count:
                continue
            p = cfg_dir / f"{cond}_t{temp:.2f}".replace(".", "_")
            p = p.with_suffix(".yaml")
            p.write_text(TEMPLATE.format(
                cond=cond, temp=temp, mean=args.mean, sd=args.sd,
                lo=args.lo, hi=args.hi, model=MODEL, sysline=sysline,
                outdir=outdir))
            plan += [str(p)] * count
        random.Random(args.rng_seed).shuffle(plan)
        plan_path = Path(f".log/livetest_v4_{cond}_plan.txt")
        plan_path.parent.mkdir(parents=True, exist_ok=True)
        plan_path.write_text("\n".join(plan) + "\n")
        rc = Counter()
        for pth in plan:
            rc[pth] += 1
        print(f"[{cond}] {len(plan)} runs, sysprompt={'YES' if sysprompt else 'no'} "
              f"-> {plan_path}  (out: {outdir})")
    print(f"temps span {temps[0]}..{temps[-1]}, weighted N({args.mean},{args.sd}) "
          f"trunc [{args.lo},{args.hi}]")


if __name__ == "__main__":
    main()
