fetcher_config:
  fetcher: "sharegpt"
  data_path: "data/seeds_unseen_hgh_500.json"
  min_messages: 3
  max_messages: 6
analyzer_config:
  analyzer: "similarity"
  analyze_window: 10
agent_configs:
  - provider: "local_hf"
    model: "/u/fash/internship-hpc-repo-template/models/end-token-A-qwen3b-v6-L15-bh"
    system_prompt: "You are a helpful assistant participating in a conversation."
    temperature: 1.0
    max_tokens: 512
    frequency_penalty: 0.0
    presence_penalty: 0.0
    top_p: 0.8
agent_selection_method: "round_robin"
history_window: 5
max_iterations: 28
max_total_characters: 1000000
output_dir: "/dais/fs/scratch/fash/results/livetest_v6_L15-bh_selfloop"
